version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli@8.0.6

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - ng build --prod

artifacts:
  
  files:
    - 'dist/my-angular-project/**/*'
    - appspec.yml